### ISSUE TITLE
Error connecting to upgrade server

### ISSUE THREAD

**Issue by tiagofreire-pt** [ShotokanZH/ipq807x_openwrt_sysupgrade_server#1]
Hi.

I installed with the instructions, but the error appear on the router while quering it:

![image](https://user-images.githubusercontent.com/41837236/207673238-6b80b846-a251-40a2-995f-0c4faf8c5094.png)

On the server:

![image](https://user-images.githubusercontent.com/41837236/207673438-347282f0-7fde-4540-895b-35a0a538ebdb.png)

Could give a hand on this?

**Comment by ShotokanZH** [comment]
Hello,
You have not followed the instructions completely: open the page on a web browser and follow the instructions that appear there :)
You are missing the device name in the url :)

**Comment by tiagofreire-pt** [comment]
In the current version of the readme, does not have any instruction to access on the browser first to get further instructions:

![image](https://user-images.githubusercontent.com/41837236/208397892-ad736cb5-7888-4df4-a99d-0b369d0e7e30.png)

**Comment by tiagofreire-pt** [comment]
PR: https://github.com/ShotokanZH/ipq807x_openwrt_sysupgrade_server/pull/2
